import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Under construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Website under construction
        </h1>

        <p className={styles.description}>
          If you need to reach out to me in the meanwhile please refer to my <a href="https://linkedin.com/in/bretanac93" target="_blank" rel="noreferrer">LinkedIn</a>
        </p>
      </main>
    </div>
  )
}

export default Home
